version: "3"
services: 
    web:
     image: saikiranreddy1808/java-mvn-privaterepos:php
     ports:
     - "8001:80"
     depends_on:
     - mysql
    mysql:
     image: saikiranreddy1808/java-mvn-privaterepos:sql
     environment:
        MY_SQL_ROOT_PASSWORD: password
     volumes:
     - db_data:/var/lib/mysql
volumes:
  db_data: {}   